@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.accessToken}}


### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "carlos@email.com",
  "password": "C12345"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/123
Authorization: Bearer {{jwtToken}}


### create user
# @name createUser

POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Maria",
  "email": "maria@email.com",
  "password": "M12345"
}

### update user
# @name updateUser

PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "email": "altograudede@email.com",
  "email": "altograu@email.com",
}

### update user password
# @name updateUserPassword


PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "currentPassword": "54321C",
  "newPassword": "C12345"
}

### Read one user
# @name readOneUser

GET {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### delete user
# @name deleteUser

DELETE {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}
