@baseUrl = http://localhost:3000

### Auth login
# @nome authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "teste@email.com",
  "password": "123456"
}

### Read one user
# @nome readOneUser
GET {{baseUrl}}/user/123

### create user
# @nome createUser

POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Dedealtograu",
  "email": "altograu@email.com",
  "password": "diaD45"
}
