@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.accessToken}}


### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "altograu@email.com",
  "password": "diaD45"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/123
Authorization: Bearer {{jwtToken}}


### create user
# @name createUser

POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Dedealtograu",
  "email": "altograu@email.com",
  "password": "diaD45"
}
